config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "publicrecipes#index"
  resources :users, only: %i[index show] do
    resources :foods, only: %i[index show new create destroy] do
      resources :recipefoods, only: %i[show new create edit update destroy]
    end
    resources :recipes, only: %i[index show create update new destroy] do
      resources :recipefoods, only: %i[show new create edit update destroy]
      resources :shoppinglists, only: %i[show]
    end
  end
  resources :publicrecipes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipefoods, foreign_key: 'food_id'
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  before_destroy :delete_recipe_foods

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :measurement_unit, presence: true

  private

  def delete_recipe_foods
    recipefoods.destroy_all
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipefoods, foreign_key: 'recipe_id'
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
end

app/models/recipefood.rb
class Recipefood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods, foreign_key: 'user_id'
  has_many :recipes, foreign_key: 'user_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user
  before_action :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show destroy]
  before_action :set_user, only: %i[index new create destroy]

  def index
    @foods = @user.foods.includes(:user)
  end

  def show; end

  def new
    @food = @user.foods.new
  end

  def create
    @food = @user.foods.new(food_params)
    if @food.save
      redirect_to user_food_path(@user, @food),
                  notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @food.destroy
    redirect_to user_foods_path(@user),
                notice: 'Food was successfully destroyed.'
  end

  private

  def set_user
    @user = current_user
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/publicrecipes_controller.rb
class PublicrecipesController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @recipes =
      Recipe.includes(:user).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipefoods_controller.rb
class RecipefoodsController < ApplicationController
  before_action :authenticate_user!

  def show
    @recipefood = Recipefood.find(params[:id])
    @recipe = @recipefood.recipe
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipefood = Recipefood.new
  end

  def create
    @recipefood = Recipefood.new(recipefood_params)
    @recipe = Recipe.find(params[:recipe_id])
    @recipefood.recipe = @recipe
    if @recipefood.save
      redirect_to user_recipe_path(@recipe.user, @recipe),
                  notice: 'Food was successfully added to recipe.'
    else
      render :new
    end
  end

  def edit
    @recipefood = Recipefood.find(params[:id])
    @recipe = @recipefood.recipe
  end

  def update
    @recipefood = Recipefood.find(params[:id])
    @recipe = @recipefood.recipe
    if @recipefood.update(recipefood_params)
      redirect_to user_recipe_path(@recipe.user, @recipe),
                  notice: 'Food was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipefood = Recipefood.find(params[:id])
    @recipe = @recipefood.recipe
    @recipefood.destroy
    redirect_to user_recipe_path(@recipe.user, @recipe),
                notice: 'Food was successfully removed from recipe.'
  end

  private

  def recipefood_params
    params.require(:recipefood).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @recipes = @user.recipes.includes(:user)
  end

  def show
    @recipe = Recipe.includes(:recipefoods).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = 'Recipe added successfully'
      redirect_to user_recipes_path(user_id: current_user.id)
    else
      flash.now[:error] = 'Error: Creating Recipe'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    if @recipe.destroy
      redirect_to user_recipes_path(user_id: current_user.id)
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    return unless @recipe.update(recipe_params)

    redirect_to user_recipe_path(user_id: current_user.id, id: @recipe.id)
  end

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :preparation_time,
      :public,
      :description,
      :cooking_time
    )
  end
end

app/controllers/shoppinglists_controller.rb
class ShoppinglistsController < ApplicationController
  before_action :authenticate_user!

  def show
    recipes = current_user.recipes.includes(recipefoods: :food)
    shoppinglist_raw = {}
    @shoppinglist = []

    recipes.each do |recipe|
      recipe.recipefoods.each do |recipefood|
        food = recipefood.food
        if shoppinglist_raw[food.id]
          shoppinglist_raw[food.id][:quantity] += recipefood.quantity
        else
          shoppinglist_raw[food.id] = {
            food: food,
            quantity: recipefood.quantity
          }
        end
      end

      update_shoppinglist(shoppinglist_raw)
    end
    @recipe = Recipe.find(params[:recipe_id])
  end

  private

  def update_shoppinglist(shoppinglist_raw)
    shoppinglist_raw.values.each do |recipefood|
      quantity = recipefood[:quantity] - recipefood[:food].quantity
      next unless quantity.positive?

      @shoppinglist << {
        food: recipefood[:food],
        quantity: quantity,
        price: recipefood[:food].price * quantity
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <% if food.user == current_user %>
      <%= button_to "Destroy", user_food_path(food.user, food), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, url: user_foods_path) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="form-field">
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div class="form-field"> 
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="form-field">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<section class="foods-index">
  <p style="color: green"><%= notice %></p>
  <div class="add-food-btn">
    <%= button_to "New food", new_user_food_path(current_user), class:"btn", method: :get %>
  </div>
  <div id="foods">
    <% if @foods.empty? %>
      <p>There are no foods yet.</p>
    <% else %>
      <table border="1">
        <thead>
          <tr>
            <th>Food</th>
            <th>Measurement Unit</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
            <td><%= link_to food.name, user_food_path(food.user, food) %></td>
              <td><%= food.measurement_unit %></td>
              <td><%= number_to_currency(food.price) %></td>
              <td><%= food.quantity %></td>
              <td>
                <%= link_to "Delete", user_food_path(food.user, food), method: :delete, data: { confirm: "Are you sure you want to delete this food?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/foods/new.html.erb
<section class="form-section">
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", user_foods_path %>
  </div>
</section>

app/views/foods/show.html.erb
<section class="foods-show">
  <p style="color: green"><%= notice %></p>

  <%= render @food  %>

  <div>
    <%= link_to "Back to foods", user_foods_path %>
  </div>
</section>

app/views/home/index.html.erb
<h1> this is home </h1>
<p> logged in as <%= current_user.email %> </p>

app/views/layouts/_navigation.html.erb
<nav class="nav">
  <% if current_user %>
    <p> Welcome:  <%=current_user.name %></p>
    <ul>
      <li><%= link_to "Recipes",  user_recipes_path(user_id: current_user.id), class: "links" %></li>
      <li><%= link_to "Foods", user_foods_path(user_id: current_user.id), class: "links" %></li>
      <li><%= link_to "Public Recipes", publicrecipes_path(), class: "links" %></li>
      <%= link_to "Log Out", destroy_user_session_path,data: { turbo_method: :delete }, class: "links" %>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "links" %></li>
      <li><%= link_to "Log In", new_user_session_path, class: "links" %></li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "recipe_index" %>
    <%= stylesheet_link_tag "public_recipe" %>
    <%= stylesheet_link_tag "recipes_show" %>
    <%= stylesheet_link_tag "foods" %>
    <%= stylesheet_link_tag "recipefoods" %>
    <%= stylesheet_link_tag "shoppinglist" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/publicrecipes/index.html.erb
<div class="precipe-list">
  <h1 class="heading-pr">Public Recipes</h1>
  <div class="precipe-container">
    <% if @recipes.empty? %>
      <p>No public recipes available.</p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="precipe-post">
          <div class="left-column">
            <%= link_to user_recipe_path(user_id: recipe.user.id, id: recipe.id) do %>
              <h2 class="precipe-title"><%= recipe.name %></h2>
            <% end %>
            <p class="precipe-user">By: <%= recipe.user.name %></p>
          </div>
          <div class="right-column">
            <% total_food_items = recipe.recipefoods.count %>
            <% total_price = recipe.recipefoods.joins(:food).sum('foods.price * recipefoods.quantity') %>
            <p class="precipe-totals">Total food items: <%= total_food_items %></p>
            <p class="precipe-totals">Total price: <%= number_to_currency(total_price) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipefoods/_form.html.erb
<%= form_with(model: [current_user, @recipe, recipefood], local: true) do |form| %>
  <% if recipefood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipefood.errors.count, "error") %> prohibited this recipefood from being saved:</h2>

      <ul>
        <% recipefood.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :food_id, "Food" %>
    <%= form.collection_select :food_id, current_user.foods, :id, :name, prompt: true %>
  </div>

  <div class="form-field">
    <%= form.label :quantity, "Quantity" %>
    <%= form.number_field :quantity %>
  </div>

  <%= form.hidden_field :recipe_id, value: @recipe.id %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipefoods/edit.html.erb
<h1>Edit Ingredient: <%= @recipefood.food.name %></h1>

<%= render "form", recipefood: @recipefood %>

<%= link_to "Back to recipe", user_recipe_path(current_user, @recipe) %>

app/views/recipefoods/new.html.erb
<section class="form-section">
  <h1>Add Ingredient<h1>

  <%= render "form", recipefood: @recipefood %>

  <br>

  <div>
    <%= link_to "Back to recipe", user_recipe_path(current_user, @recipe) %>
  </div>
</section>

app/views/recipefoods/show.html.erb
<section class="recipefoods-show">
  <h2>Show Ingredient: <%= @recipefood.food.name %></h2>

  <p><%= "Quantity: #{@recipefood.quantity}" %></p>

  <div>
    <%= button_to "Edit", edit_user_recipe_recipefood_path(current_user, @recipe, @recipefood) %>
    <%= button_to "Delete", user_recipe_recipefood_path(current_user, @recipe, @recipefood), method: :delete, data: { confirm: "Are you sure you want to delete this ingredient?" } %>
  </div>

  <%= link_to "Back to recipe", user_recipe_path(current_user, @recipe) %>
</section>

app/views/recipes/index.html.erb
<section>
  <h1>Here is list of recipe</h1>
  <button type="button" class="recipe-button"><%= link_to "Add Recipe", new_user_recipe_path(user_id: current_user.id) %></button>

  <% @recipes.each do |recipe| %>
    
      <div class="recipe-container">
        <div class="recipe-header">
        <%= link_to user_recipe_path(user_id: recipe.user.id, id: recipe.id), class: "recipe-post" do %>
          <h2 class="recipe-title"><%= recipe.name %></h2>
          <% end %>
  <%= form_with url: user_recipe_path(user_id: recipe.user.id, id: recipe.id), method: :delete do |form| %>
    <%= form.submit "REMOVE", class: "delete-text" %>
  <% end %>
        </div>
        <div class="recipe-description">
          <h4><%= truncate(recipe.description, length: 150, omission: " . . .") %></h4>
        </div>
      </div>
  <% end %>
</section>

app/views/recipes/new.html.erb
<div class="form-section">
  <h1>Create a New Recipe</h1>

  <%= form_with model: @recipe, url: user_recipes_path(user_id: current_user.id), method: :post do |form| %>
    <div class="form-field">
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :description %>
      <%= form.text_area :description, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :preparation_time %>
      <%= form.text_field :preparation_time, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :cooking_time %>
      <%= form.text_field :cooking_time, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :public %>
      <%= form.check_box :public %>
    </div>

    <div style="text-align: center;">
      <%= form.submit "Create Recipe" , class: "btn" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<section class="recipe-show">
  <p style="color: green"><%= notice %></p>

  <h1> <%= @recipe.name %> </h1>

  <div>
    <div class="recipe-show-headline">
      <div class="recipe-show-attr">
        <p>
          <strong>Preparation time:</strong>
          <%= @recipe.preparation_time %> minutes
        </p>
        <p>
          <strong>Cooking time:</strong>
          <%= @recipe.cooking_time %>
        </p>
      </div>
      <div class="toggle-switch-container">
        <%= "Public" %>
        <label class="switch">
          <%= form_with model: @recipe, url: user_recipe_path(current_user, @recipe), method: :patch do |f| %>
            <%= f.hidden_field :public, value: !@recipe.public %>
            <%= f.submit "", class: "btn btn-primary" %>
          <% end %>
          <input type="checkbox" <%= @recipe.public ? "checked" : "" %> disabled>
          <span class="slider round"></span>
        </label>
      </div>
    </div>

    <p><%= @recipe.description %></p>
    <br>

    <div class="recipe-show-btns">
      <%= button_to "Generate Shopping List", user_recipe_shoppinglist_path(current_user, @recipe), method: :get %>
      <%= button_to "Add Ingredient", new_user_recipe_recipefood_path(current_user, @recipe), method: :get %>
    </div>
    <br>

    <hr> <br>

    <% if @recipe.recipefoods.empty? %>
      <p>There are no ingredients yet.</p>
    <% else %>
      <table border="1">
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.recipefoods.each do |recipefood| %>
            <tr>
              <td><%= link_to recipefood.food.name, user_food_path(recipefood.food.user, recipefood.food) %></td>
              <td><%= "#{recipefood.quantity} #{recipefood.food.measurement_unit}" %></td>
              <td><%= number_to_currency(recipefood.food.price * recipefood.quantity) %></td>
              <td>
                <%= link_to "Modify", edit_user_recipe_recipefood_path(current_user, @recipe, recipefood) %>
                <%= link_to "Delete", user_recipe_recipefood_path(current_user, @recipe, recipefood), method: :delete, data: { confirm: "Are you sure you want to delete this ingredient?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/shoppinglists/show.html.erb
<section class="shoppinglist-show">
  <p style="color: green"><%= notice %></p>

  <h1>Shopping List</h1>
<% if @shoppinglist.empty? %>
<p> List is empty </p>
<% else @shoppinglist.empty? %>

  <div class="shoppinglist-show-headline">
    <p>
      Ammout of food to buy: <%= @shoppinglist.count %>
    </p>
    <p>
      Total value of food needed: <%= number_to_currency(@shoppinglist.sum { |item| item[:price]}) %>
    </p>
  </div>

  <Table border="1">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @shoppinglist.each do |recipefood| %>
        <tr>
          <td><%= link_to recipefood[:food].name, user_food_path(current_user, recipefood[:food]) %></td>
          <td><%= "#{recipefood[:quantity]} #{recipefood[:food].measurement_unit}" %></td>
          <td><%= number_to_currency(recipefood[:price]) %></td>
        </tr>
      <% end %>
    </tbody>
  </Table>
<% end %>
  <br>

  <%= link_to "Back to Recipe", user_recipe_path(current_user, @recipe) %>
</section>